### ISSUE TITLE
Debricking

### ISSUE THREAD

**Issue by bingo619** [ludwig-v/wireless-carplay-dongle-reverse-engineering#1]
Hi Mate,

Thanks for the great work. How can I debrick my carlinkit using your bin file?

Cheers.

**Comment by ludwig-v** [comment]
At the moment it is still not possible:
- Flashing a valid dump to a bricked unit is not working.
- Flashing a valid dump from another unit on a valid unit is bricking it.

I have 3 bricked units at home, it is still a work in progress.

**Comment by bingo619** [comment]
Thanks for the reply. Please update if you got it working.

**Comment by WERNERHELLY** [comment]
Hi Ludwig
i have the carplay2air updated with your U2w update 
but something happened
i have only a blue light on the adapter and no red solid light 
adapter is not working anymore and can not update it anymore
i think Bricked pffff
is there any solution for this

pls help me

werner.hellemonds@telenet.be

**Comment by zombiRon** [comment]
> At the moment it is still not possible:
> 
> - Flashing a valid dump to a bricked unit is not working.
> 
> - Flashing a valid dump from another unit on a valid unit is bricking it.
> 
> 
> 
> I have 3 bricked units at home, it is still a work in progress.

On the first boot after flashing a valid dump, does the unit flash blue-red and get faster and faster until a solid dim blue light is left??

**Comment by ludwig-v** [comment]
Closing as this is not an issue, just opened "Discussions" tab here: https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/discussions
