### ISSUE TITLE
Flash dump 20210331 RED  UI

### ISSUE THREAD

**Issue by leonardosalles** [ludwig-v/wireless-carplay-dongle-reverse-engineering#103]
Is there any additional dump for this version? It seems that Green UI dump causes hardware error on Red UI firmwares, I bricked  my device and was able to restore it but I am receiving a hardware  error since my one is the Red UI and @brokens dump is related to Green UI, anyone can help on pick this particular dump?

**Comment by ludwig-v** [comment]
Just flash the dump and update to last (official) version using USB, it will fix "hardware" issues ;)
