### ISSUE TITLE
Install Custom Firmware on Carlinkit v3.0 device...

### ISSUE THREAD

**Issue by dmavromatis** [ludwig-v/wireless-carplay-dongle-reverse-engineering#110]
I have a V3.0 Device -- I rolled back to U2W_AUTOKIT_Update_2020.12.25.1732_ROLLBACK.img

Checked the internal webpage, shows that version.

However, when I try to install the CFW 2021.08.24_BASED firmware by placing on USB named as:
U2W_AUTOKIT_Update.img (or U2W_Update.img)

I get nothing...

however, if I download official (2021.08.24 named U2W_AUTOKIT_Update.img) and place on USB, it updates... any ideas?

Has anyone installed the custom firmware on a v3.0 device? 

If so, what steps did you take?

(I have successfully installed CFW on v2.0 devices in the past)

**Comment by ludwig-v** [comment]
**`Warning: Official firmware 2021.03.06 or later can only be downgraded using U2W_Update_2020.11.10.2138_ROLLBACK.img`**

Please read ..

Rename U2W_Update_2020.11.10.2138_ROLLBACK.img to U2W_AUTOKIT_Update.img, then 2021.08.24 named U2W_AUTOKIT_Update.img to U2W_Update.img and you will be on AUTOKIT CFW.
