### ISSUE TITLE
Install Custom Firmware on Carlinkit v3.0 device...

### ISSUE THREAD

**Issue by dmavromatis** [ludwig-v/wireless-carplay-dongle-reverse-engineering#111]
@ludwig-v  that does not work -- I'm currently running v3.0 device, with factory firmware 2021.07.05.2308.

Rename U2W_Update_2020.11.10.2138_ROLLBACK.img to U2W_AUTOKIT_Update.img.

Place USB drive into dongle plugged into power adapter.  Its does nothing... 

However, placing official (2021.08.24 named U2W_AUTOKIT_Update.img) and place on USB, it updates.

**Comment by ludwig-v** [comment]
Please stop opening issues for support requests, there is a discussion tab.

You are doing something wrong, I already explained everything here:
https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/issues/99#issuecomment-895229809

**Comment by ludwig-v** [comment]
Please stop opening issues for support requests, there is a discussion tab.

You are doing something wrong

Put U2W_Update_2020.11.10.2138_ROLLBACK.img on a USB Key and rename it to **U2W_AUTOKIT_Update.img if Red UI** or **U2W_Update.img if Blue UI**.

**Comment by totalitarian** [comment]
Are we sure U2W_Update_2020.11.10.2138_ROLLBACK.img works for v3.0?
