### ISSUE TITLE
hardware schematic

### ISSUE THREAD

**Issue by liker292** [ludwig-v/wireless-carplay-dongle-reverse-engineering#12]
Anybody has the hardware schematic diagram please?

**Comment by iDoka** [comment]
Making reverse engineering PCB to recovery entire schematic diagram is almost impossible (expensive).
Also the board has elements without any marking (SOIC8  body).
I suppose partly recovery is possible based on iMX6 reference design.

If I could know the purpose of this, it will be easier to advise something

**Comment by KrutavShah** [comment]
I have some experience with hardware design, so given a list of parts that are in each dongle like MFI chip, I can build together something that may work. This project also seems to have a dump of the flash, so if that works then we may be able to hack together a board design that can be ordered and built DIY.

**Comment by KrutavShah** [comment]
https://community.nxp.com/t5/i-MX-Processors/About-mounting-MFi-authentication-chip-MFI-337-S3959-on-i-MX/td-p/972575

So I found a link that talks about the android auto authentication chip listed earlier "3959" and it may be a part that is manufactured by NXP, so it shouldn't be too hard to get a hold on.

**Comment by ludwig-v** [comment]
Closing as this is not an issue, just opened "Discussions" tab here: https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/discussions
