### ISSUE TITLE
carlinkit u2w plus no power after update

### ISSUE THREAD

**Issue by Kavamaro** [ludwig-v/wireless-carplay-dongle-reverse-engineering#129]
Hello. 

I started the update for the carplay dongle and it was completed successfully but the device wont startup. 
Please check the attached images for the update process and feedback how to fix it by offline update or rollback.  
i downloaded the roll back img but no luck as the device not powering when i plug it to a charger.

**Comment by Kavamaro** [comment]
![image](https://user-images.githubusercontent.com/97364420/155417462-3c81c0f4-42e7-48a7-b0e1-eb0744635aa3.jpeg)

**Comment by Kavamaro** [comment]
![image](https://user-images.githubusercontent.com/97364420/155417528-2f90d00b-f676-466e-8f8c-8a339bc92914.png)
![image](https://user-images.githubusercontent.com/97364420/155417576-33afe5e3-353c-4ef6-af3b-2eb0176db70b.png)

**Comment by ludwig-v** [comment]
Please use discussions tab, issues are related to reverse engineering not manufacturer support.
