### ISSUE TITLE
Dropbear

### ISSUE THREAD

**Issue by LiveWire1968** [ludwig-v/wireless-carplay-dongle-reverse-engineering#13]
Using drop bear seems pretty easy. I dropped the files on a fat32 usb. Let the carlink turn on, insert usb.
Connect to GMBB, try to ssh to unit. Connection refused. I can ping 192.168.50.2 fine. Redlight doesnt go out.
Any information would be appreciated.

**Comment by jsm174** [comment]
Are you using one of the custom firmwares already?

**Comment by LiveWire1968** [comment]
> Are you using one of the custom firmwares already?

I actually jumped back on here to edit or respond. I used the custom firmware, then dropbear worked fine. Sorry for that.
I was trying to figure out how to remove old vehicles. Deleting them from the headunit doesnt seem to change things.
