### ISSUE TITLE
Navigation HUD support

### ISSUE THREAD

**Issue by arvind-balaji** [ludwig-v/wireless-carplay-dongle-reverse-engineering#149]
Carplay seems to support the ability to [display navigation information on a secondary display.](https://www.autoevolution.com/news/apple-carplay-navigation-now-available-on-the-bmw-digital-instrument-cluster-148335.html). 

Is there any way to create a script to access and transmit the data that would be used for a HUD?

**Comment by ludwig-v** [comment]
Carlinkit only provides a binary file and everything is inside, we can't add new functionalities without reinventing the wheel
