### ISSUE TITLE
Any way to measure/change sound quality?

### ISSUE THREAD

**Issue by alexvnesta** [ludwig-v/wireless-carplay-dongle-reverse-engineering#15]
sorry, this is more of a question than an issue. I didn’t know where else I could talk to people familiar with the device.

I am using a dongle for wireless CarPlay. Occasionally I notice strange distorted crackling sounds when using wireless CarPlay only. 

I’m wondering if anyone has taken a look into how the audio is streamed? Is it cd quality or a compressed format to improve latency? Is there any way to improve the audio quality being streamed?

**Comment by LiveWire1968** [comment]
Have you looked at the web ui of the unit. 192.168.50.2 while connected to it. Theres a option to change it to dvd quality

**Comment by ludwig-v** [comment]
Closing as this is not an issue, just opened "Discussions" tab here: https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/discussions
