### ISSUE TITLE
Carlinkit CPC200-CP2A with an aftermarket display

### ISSUE THREAD

**Issue by Igor888991** [ludwig-v/wireless-carplay-dongle-reverse-engineering#151]
Hello! I bought a Carlinkit for my car's media center, but I can't connect it. The screen just show me the it's loading. I've trying everything that I can and I'm not able to make it work. I would like to know if it's some way to make it connect. Thank you, guys! 
![FB_IMG_1674245751240](https://user-images.githubusercontent.com/122753630/213797649-7a14f2a2-6c76-4750-a768-ed160809ea75.jpg)
![FB_IMG_1674245755382](https://user-images.githubusercontent.com/122753630/213797652-7b09be51-6d9a-458b-807b-eb2342759221.jpg)

**Comment by ludwig-v** [comment]
Please contact Carlinkit support, it is a reverse engineering repo here ;)
