### ISSUE TITLE
Delay power to dongle when starting up car

### ISSUE THREAD

**Issue by MrPickles2009** [ludwig-v/wireless-carplay-dongle-reverse-engineering#17]
It is already available on 192.168.50.2 ...

_Originally posted by @ludwig-v in https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/issues/16#issuecomment-774274486_

**Comment by MrPickles2009** [comment]
Currently you can only edit media delay. I don't see a setting for delaying power to the device:
![image](https://user-images.githubusercontent.com/20229190/107090022-93c43c80-67cd-11eb-8af3-ad3376b8fe52.png)

**Comment by ludwig-v** [comment]
You are not using the latest version no wonder why
