### ISSUE TITLE
Running on Rasppberry pi

### ISSUE THREAD

**Issue by CimeM** [ludwig-v/wireless-carplay-dongle-reverse-engineering#18]
Bonjour, 

Is it possible to load the project up to a different ARM like Raspberry PI? I am looking for a way to connect with carplay without dongles on a RPI.

Kind regards

**Comment by hbouhadji** [comment]
Hello,

I am interesting about the same, but we need to reverse theses binaries: (as said on https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/issues/5) 

https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/blob/master/Extracted/28102020/usr/sbin/fakeiOSDevice
https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/blob/master/Extracted/28102020/usr/sbin/AppleCarPlay

But I think there is a custom chip to spoof the apple authentication, so I'm not sure it can be done without additional hardware

**Comment by iDoka** [comment]
May be it might be useful https://github.com/45clouds/WirelessCarPlay (The hole idea is to use Raspberry Pi hardware)
for substitute AppleCarPlay binaries with builded from sources (with necessary changes)

**Comment by Snirpo** [comment]
The small "3959" chip in the bottom of this picture (https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/blob/master/Pictures/CARLINKIT_V2/1.jpeg) is 90% sure an MFI chip. The CarPlay2Air has it, Carlinkit has it and also some other chinese Headunit I have has it. It's this chip: MFI337S3959. So they are just putting an MFI chip on without having a license... And most probably without an MFI chip you cannot make it work.

**Comment by THX723** [comment]
Sounds about right!

**Comment by KrutavShah** [comment]
https://community.nxp.com/t5/i-MX-Processors/About-mounting-MFi-authentication-chip-MFI-337-S3959-on-i-MX/td-p/972575

So I found a link that talks about the android auto authentication chip listed earlier "3959" and it may be a part that is manufactured by NXP, so it shouldn't be too hard to get a hold on.

**Comment by ludwig-v** [comment]
Closing as this is not an issue, just opened "Discussions" tab here: https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/discussions
