### ISSUE TITLE
A new version has been released for V4. 2024.01.10.0953 

### ISSUE THREAD

**Issue by xikamo** [ludwig-v/wireless-carplay-dongle-reverse-engineering#188]
[2024.01.10.0953.zip](https://github.com/user-attachments/files/15540185/2024.01.10.0953.zip)

**Comment by ludwig-v** [comment]
https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/commit/72131a452f264996cfebc8ff311fa6591a89b74e

Thank's ;)
