### ISSUE TITLE
Can't find 88x2bs.ko in filesystem

### ISSUE THREAD

**Issue by iDoka** [ludwig-v/wireless-carplay-dongle-reverse-engineering#2]
My goal is build my own clone of CarPlay dongle on custom HW with RTL8822BS WiFi/BT SDIO module (as in original dongle).
In file `/script/load_bluetooth_wifi.sh` mentioned `88x2bs.ko`:
```
insmod /tmp/88x2bs.ko
```
but I can't find `88x2bs.ko` anywhere in filesystem.

I'll appreciate any help and suggestion about  `88x2bs.ko` locations.

**Comment by ludwig-v** [comment]
This file is not present, the driver is probably included inside the kernel and this insmod is for testing purposes only.
It is probably coming from [here](https://github.com/morrownr/88x2bu) anyway so you can rebuild it:
`ifeq ($(CONFIG_SDIO_HCI), y)
MODULE_NAME = 88x2bs
endif
`

**Comment by iDoka** [comment]
I'm afraid but it seems 88x2bu.ko doesnt fit to substitute for 88x2bs.ko

* `88x2bu.ko` fit to RTL8822BU (USB version)
* `88x2bs.ko` fit to RTL8822BS (SDIO version)

I found that [repo](https://github.com/ChalesYu/rtl8822bs-aml) but it seems experimental driver (w/o Bluettoth support which needs for CarPlay connection).

Do you know any approaches for extracting `88x2bs.ko` from kernel?

**Comment by ludwig-v** [comment]
You didn't check what I wrote, in the Makefile you can see that if CONFIG_SDIO_HCI is enabled inside kernel settings then the driver is built as 88x2bs(.ko) so it should work.

Extracting the module from the kernel won't make it easier, you will have to use the exact same kernel to make it work.

**Comment by iDoka** [comment]
Sorry for my carelessness.
Indeed,  despite to description they also supports RTL8822BS.
I will try to use it.

**Comment by ludwig-v** [comment]
https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/blob/master/Extracted/28102020/tmp/88x2bs.ko

From latest firmware version it is available ;)

**Comment by iDoka** [comment]
Wow!.. It's really cool!
Much thanks!
