### ISSUE TITLE
Strange power behaviour

### ISSUE THREAD

**Issue by Pantman** [ludwig-v/wireless-carplay-dongle-reverse-engineering#20]
I've noticed some strange behaviour regarding how the dongle boots when powered. My car gives power to the USB when the car is approached (with key in pocket). When this happens, I can see the red light on the device appear, and if I insert a USB stick with the dropBear script, the LED turns off. However, the Wifi never starts, and I can't connect to it.

This is different from when I connect the dongle to a USB charger. The wifi appears online a few seconds after connection.

If I turn on my car, eventually the dongle boots, and the wifi appears.

I'm curious why this behaviour occurs. It seems to me that it might be possible for the dongle to mostly finish booting before I start the car, which could significantly increase the speed of carplay connection when first starting the car. 

Any idea where I should look to investigate the boot sequence?

**Comment by ludwig-v** [comment]
Closing as this is not an issue, just opened "Discussions" tab here: https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/discussions
