### ISSUE TITLE
Difference between U2W and U2W_AUTOKIT

### ISSUE THREAD

**Issue by ANTONBORODA** [ludwig-v/wireless-carplay-dongle-reverse-engineering#21]
I recently received a Carlinkit dongle and it looks the same as everyone's else, but the firmware is 2020.12.25.1731 and the URL it's grabbing the update from is different: mnt/downloads/2021-01-12/yunlian/U2W_AUTOKIT_Update_2020.12.25.1731.img
Does anyone know what's the difference between this and standard U2W dongles?

**Comment by milesking** [comment]
It seems the variant you got is the android version.

**Comment by ANTONBORODA** [comment]
> It seems the variant you got is the android version.

No, it works with my non-android head unit.

**Comment by milesking** [comment]
> > It seems the variant you got is the android version.
> 
> No, it works with my non-android head unit.
> Maybe they are merging them now?
Probably, your dongle is compatible with both CarPlay and autokit.apk.

**Comment by ANTONBORODA** [comment]
> > > It seems the variant you got is the android version.
> > 
> > 
> > No, it works with my non-android head unit.
> > Maybe they are merging them now?
> > Probably, your dongle is compatible with both CarPlay and autokit.apk.

Any way to test it? I'm just curious. Will connecting this to Android tablet with OTG and autokit.apk trigger the carplay on the tablet? Or there's something else that needs to be done?

**Comment by ludwig-v** [comment]
Did you open it ? That would be cool to update the main README for details of this variant (Flash type, Wifi chip), also with internal pictures, I would say they changed the flash from 16MB to 32MB, the UI is better looking and sized 1.5MB instead of 252KB on previous devices

**Comment by ANTONBORODA** [comment]
> Did you open it ? That would be cool to update the main README for details of this variant (Flash type, Wifi chip), also with internal pictures, I would say they changed the flash from 16MB to 32MB, the UI is better looking and sized 1.5MB instead of 252KB on previous devices

No, but if you would like me to do so I will. 
Gonna post pictures ASAP.

**Comment by ANTONBORODA** [comment]
By the way, plugging it into a tablet doesn’t seem to work, at least on mine. AutoKit just says “plug the device” as if it’s not connected. It either needs an actual car head unit or the firmware is actually incomplete.

**Comment by ANTONBORODA** [comment]
Photos are in


![C8753B00-5D1D-4EFD-90DD-CD2FC9540FD7](https://user-images.githubusercontent.com/1519436/110251251-64e5e580-7f88-11eb-90b0-7eb7b050e377.jpeg)
![5C3531E0-8EFB-4D7A-A0FD-032C1DE9CFAC](https://user-images.githubusercontent.com/1519436/110251255-69aa9980-7f88-11eb-9b32-a2fdf8fe1324.jpeg)
![5EE5B7DE-B0E0-416A-B458-4681D7D7334E](https://user-images.githubusercontent.com/1519436/110251260-6a433000-7f88-11eb-95fe-b5d97770cb1e.jpeg)
![29878108-DA9C-4798-857D-9E4C5255E5CA](https://user-images.githubusercontent.com/1519436/110251264-6adbc680-7f88-11eb-988c-8fbdb9848a30.jpeg)
![6CDAF824-8E52-4615-B15F-09140BC1EA1C](https://user-images.githubusercontent.com/1519436/110251267-6b745d00-7f88-11eb-831c-76d3c9ef0988.jpeg)

**Comment by ludwig-v** [comment]
Thank you, seems to be exactly the same device, can't read SOP8 Flash part numbers

![?](https://i.imgur.com/FphsN6x.jpg)

**Comment by ANTONBORODA** [comment]
Was a little bit hard to capture but here you go
![F41FB608-C7B4-4F8C-A6D7-402145C9A9F7](https://user-images.githubusercontent.com/1519436/110251563-c5295700-7f89-11eb-9ae0-f8c998d7944d.jpeg)

**Comment by ludwig-v** [comment]
Thank's !

It is the exact same flash, nothing changed at all, unexpected !

**Comment by ANTONBORODA** [comment]
Well, it’s all in software then. Very strange that it’s called autokit. I’m really curious if it’s supposed to work with a tablet with APK installed or not. I’ll test on a few more tablets on Wednesday, I have only a very old intel based android tablet ATM.

**Comment by ludwig-v** [comment]
I think it is just a new UI, nothing more 

I've been able to put the new UI inside 2021.02.02 firmware and flash it on my "old" Carlinkit V2

![New UI](https://i.imgur.com/9ZC5Qih.jpg)

**Comment by THX723** [comment]
Amazing how a bit of added thought would make the UI look more polished. Well done!

**Comment by Pantman** [comment]
Tried putting the new ui.tar.gz on my U2W, but annoyingly it wouldn't fit. I guess I have the older model. df says root file system is only 11MiB. Looking at the contents, there are resource images for various resolutions. I guess some could be trimmed...

**Comment by milesking** [comment]
> I think it is just a new UI, nothing more
> 
> I've been able to put the new UI inside 2021.02.02 firmware and flash it on my "old" Carlinkit V2
> 
> ![New UI](https://camo.githubusercontent.com/82e916a5a42e69ec1c8ce8a97e318a88f7265426dcce5b48a606b263ec519fec/68747470733a2f2f692e696d6775722e636f6d2f395a43355169682e6a7067)

The new UI looks better. By the way, the "old" UI is laggy on my Honda, how about the new one.

**Comment by kentherzz** [comment]
I found another picture of this interface, presumably the same but with different colors.
[https://forums.macrumors.com/attachments/carplay-png.1731260](url)
Maybe the color changes based on which car its connected to?

**Comment by ludwig-v** [comment]
Closing as this is not an issue, just opened "Discussions" tab here: https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/discussions
