### ISSUE TITLE
peugeot 3008 (2020 edition) -> running script to fake navigation running?

### ISSUE THREAD

**Issue by Somberland** [ludwig-v/wireless-carplay-dongle-reverse-engineering#23]
my peugeot 3008 requires "navigartion-app" to run in order to use carplay. with iphone it obviously works but carlinkit won't show anything on my dashboard.

any ideas how to fix this or do I have to hope that the manufacturer will fix this somehow? -> who can i contact for this best? the facebook/whatsapp support seems to be completely clueless :X

**Comment by ludwig-v** [comment]
Closing as this is not an issue, just opened "Discussions" tab here: https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/discussions
