### ISSUE TITLE
Possible to change name of the device?

### ISSUE THREAD

**Issue by kentherzz** [ludwig-v/wireless-carplay-dongle-reverse-engineering#24]
Is it possible to change the name of the device using script U2W.sh? I am looking into ways to change the name of both the bluetooth interface and the Wifi SSID so I can have consistent name showing up both in iOS and when the device boot up.

I found following files:
/etc/bluetooth_name
/etc/wifi_name

I thought about writing a simple rename into the script which gets executed. There must also be some code that is detecting the type of car when you plug it in as there seem to be a name like "VOLKSW-0000". Does anyone know in the code where we can find this identification - if so it should be possible to change the behaviour.

**Comment by ludwig-v** [comment]
Closing as this is not an issue, just opened "Discussions" tab here: https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/discussions
