### ISSUE TITLE
Hardware Differences of U2W based dongles?

### ISSUE THREAD

**Issue by dmavromatis** [ludwig-v/wireless-carplay-dongle-reverse-engineering#25]
Hi!

I have both the Carlinkit CpC200-U2W Plus and the CPlay2Air.

I figured the Carlinkit (ordered directly from them) was a better device since it uses 5ghz WiFi whereas I think the CPlay2Air uses 2.4ghz.  Not sure if that assumption is true or not.

However, in my vehicle, running identical firmware and settings, the CPlay2Air performance is better over the Carlinkit.  In particular, the screen taps and map dragging.  The Carlinkit has a good couple seconds of delay where as the CPlay2Air is 1 or less.

Any ideas why this would be the case?  

Also, do we have any hardware specs for the different dongles?

**Comment by ludwig-v** [comment]
Most your questions are already answered if you took the time to look at pictures: no difference except a powered wifi antenna on v2

Closing as this is not an issue, just opened "Discussions" tab here: https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/discussions
