### ISSUE TITLE
Downgrade/Flash Wiki ?

### ISSUE THREAD

**Issue by gerdy001** [ludwig-v/wireless-carplay-dongle-reverse-engineering#26]
Hello. 

I need Help!!

My Device has until update to Official 2021.03.06 an Connection Problem. It is connection to my iPhone via Bluetooth and then its loosing the connection and so on. I don't get the Apple CarPlay Screen. Only one time it was showing an wifi Error

![IMG_2273](https://user-images.githubusercontent.com/61235244/111024707-80b21700-83e0-11eb-8a29-dd08568e8b2e.jpeg)
![IMG_2274](https://user-images.githubusercontent.com/61235244/111024727-99223180-83e0-11eb-88c0-8009f6d5cdda.jpeg)

Can anyone give a Wiki how to downgrade or flash the device. I can do it on a Mac and on a Windows.

**Comment by ludwig-v** [comment]
If you use original 2021.03.06 firmware the only way to downgrade is to use the Rollback function on 192.168.50.2, no other solution for the moment

**Comment by gerdy001** [comment]
Or waiting for the next update and do it via USB?

Gruß
Gerhard

Am 14.03.2021 um 15:46 schrieb Ludwig ***@***.***>:

﻿

If you use original 2021.03.06 firmware the only way to downgrade is to use the Rollback function on 192.168.50.2, no other solution for the moment
