### ISSUE TITLE
UI_DLL.php - Bug

### ISSUE THREAD

**Issue by IcedLatte5** [ludwig-v/wireless-carplay-dongle-reverse-engineering#27]
c:\php>php UI_DLL.php
PHP Warning:  mkdir(): No such file or directory in C:\php\UI_DLL.php on line 191
Error: Can't create "/c:\php" directory, check your rights

The script is failing when run on Windows PHP, it is putting a / in the front making the path fail when attempting to create the files.

**Comment by ludwig-v** [comment]
https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/commit/a425a5e2ae2694db82fff7790c98315663732d98

**Comment by IcedLatte5** [comment]
Hi, 

Still some issues.

When unpacking it goes most of the way and then this: 

 Unpacked "searchresultbkg.png" (70939 B) from rc.dll
- Unpacked "listdown0.png" (517 B) from rc.dll
- Unpacked "listdown1.png" (1160 B) from rc.dll
- Unpacked "listup0.png" (497 B) from rc.dll
- Unpacked "listup1.png" (1139 B) from rc.dll
- Unpacked "search0.png" (681 B) from rc.dll
- Unpacked "search1.png" (1284 B) from rc.dll
- Unpacked "dbutleft.png" (842 B) from rc.dll
- Unpacked "dbutleftp.png" (727 B) from rc.dll
- Unpacked "dbutmid.png" (145 B) from rc.dll
- Unpacked "dbutmidp.png" (114 B) from rc.dll
- Unpacked "dbutright.png" (873 B) from rc.dll
- Unpacked "dbutrightp.png" (751 B) from rc.dll
- Unpacked "settingbkg.png" (89050 B) from rc.dll
- Unpacked "ratio_yes.png" (233 B) from rc.dll
- Unpacked "ratio_no.png" (75 B) from rc.dll
- Unpacked "home.png" (589 B) from rc.dll
- Unpacked "Language.png" (2738 B) from rc.dll
- Unpacked "upline.png" (632 B) from rc.dll
- Unpacked "downline.png" (632 B) from rc.dll
- Unpacked "homephonebkg.png" (64171 B) from rc.dll
- Unpacked "hline.png" (411 B) from rc.dll
- Unpacked "searchpagebkg.png" (124322 B) from rc.dll
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 33554440 bytes) in C:\php\UI_DLL.php on line 154

and Repacking failure (without any modifications):

it goes most of the way and then

- Packed "downline.png" (399 B) in new/rc.dll
- Packed "homephonebkg.png" (63745 B) in new/rc.dll
- Packed "hline.png" (364 B) in new/rc.dll
- Packed "searchpagebkg.png" (126132 B) in new/rc.dll
PHP Warning:  getimagesize(c:\php\ui\Riddle\Theme0-CarlinKit\1280x/searchresultbkg.png): Failed to open stream: No such file or directory in C:\php\UI_DLL.php on line 104
PHP Warning:  imagecreatefrompng(c:\php\ui\Riddle\Theme0-CarlinKit\1280x/searchresultbkg.png): Failed to open stream: No such file or directory in C:\php\UI_DLL.php on line 105
PHP Fatal error:  Uncaught TypeError: imagealphablending(): Argument #1 ($image) must be of type GdImage, bool given in C:\php\UI_DLL.php:106
Stack trace:
#0 C:\php\UI_DLL.php(106): imagealphablending()
#1 {main}
  thrown in C:\php\UI_DLL.php on line 106
