### ISSUE TITLE
Possible to enable serial port?

### ISSUE THREAD

**Issue by jsm174** [ludwig-v/wireless-carplay-dongle-reverse-engineering#3]
Hello!

Just wanted to say this is a great project!

Back in February, I soldered on a header in the hopes the serial port was open. It definitely appeared like there was something going on, but I could not seem to find the correct settings / baud rate etc.

```
[    0.002361] console [tty0] enabled
.
.
.
  0.242783] 2020000.serial: ttymxc0 at MMIO 0x2020000 (irq = 58, base_baud = 5000000) is a IMX
[    0.244548] 21e8000.serial: ttymxc1 at MMIO 0x21e8000 (irq = 59, base_baud = 5000000) is a IMX
[    0.245785] 21ec000.serial: ttymxc2 at MMIO 0x21ec000 (irq = 60, base_baud = 5000000) is a IMX
```

![IMG_6114](https://user-images.githubusercontent.com/1197137/98164121-ce0dfd00-1eb1-11eb-9e07-c715d4e46dc4.jpg)
![IMG_4638](https://user-images.githubusercontent.com/1197137/98164349-1fb68780-1eb2-11eb-885c-892a5befa0b2.jpg)

Have you had any luck with the serial port?

In my truck, 9 out of 10 times I manually have to unplug and replug the device in. I figured maybe I could add an artificial delay to the scripts during startup. (I think MyLink just takes too long to startup).

**Comment by ludwig-v** [comment]
I already tried that too and had the same result
UART2 is dedicated to Bluetooth so that's probably why you are seeing activity but UART1 seems to be disabled

**Comment by jsm174** [comment]
@ludwig-v - Thanks. I'm wonder if this is related: https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/blob/8b448e57380f22e3541656b93fb4ab010e3d810f/Firmware/U2W_Update_03062020/etc/inittab#L2

**Comment by ludwig-v** [comment]
Closing as this is not an issue, just opened "Discussions" tab here: https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/discussions
