### ISSUE TITLE
Can it deploy in Raspberry Pi

### ISSUE THREAD

**Issue by Quinn-Liu** [ludwig-v/wireless-carplay-dongle-reverse-engineering#33]
I think raspberry pi is a very ideal device to achieve u project，is there any other reason to choose i.MX 6?
I know new NAC/RCC SoC is i.MX 6

**Comment by Quinn-Liu** [comment]
I think the best deivce is raspberry pi zero wireless or CM4，or raspberry pi4 is much too big

**Comment by ludwig-v** [comment]
This is not an issue, please use "Discussions"
