### ISSUE TITLE
USB stick won't be recognized

### ISSUE THREAD

**Issue by K3vb3rt** [ludwig-v/wireless-carplay-dongle-reverse-engineering#40]
Hi guys,

I tried several versions but none of them will be recognized by my Carlinkit 2.0. Tried different usb drives, the light stays red and device is not flashing.

Do you have any recommendations?

Thanks in advance.

**Comment by ludwig-v** [comment]
The "Issues" tab is for issues linked to the repo not the device it self, please use "Discussions" instead

Your device is most likely bricked if it currently doesn't work.
