### ISSUE TITLE
DIY Unit

### ISSUE THREAD

**Issue by sa7mon** [ludwig-v/wireless-carplay-dongle-reverse-engineering#5]
Do you know if it's possible to use this firmware to create your own DIY version of this device? It seems like the Raspberry Pi Zero has very similar hardware (ARM processor, Bluetooth, WiFi).

**Comment by ludwig-v** [comment]
It is not the purpose of this repo, @iDoka has a similar idea, you should join your forces on a dedicated repo (it implies relying on unknown proprietary binaries)
