### ISSUE TITLE
IMX6 or AT91SAM9260

### ISSUE THREAD

**Issue by liker292** [ludwig-v/wireless-carplay-dongle-reverse-engineering#68]
Are you using imx6 or AT91SAM9260 ?
you say use i.MX6 in Hardwave infonation, but in "picture" i found it is AT91SAM9260.

**Comment by CiNcH83** [comment]
The picture is misleading for several reasons:
- Atmel/Microchip AT91SAM9260 has no DDR3 controller, see DDR3 RAM on picture
- Atmel/Microchip AT91SAM9260 has no SDIO for RTL8822BS
- Linux syslog clearly states that the SoC is an i.MX6 (which makes a lot of sense as NXP/Freescale provide MFi development kits for Apple audio accessories)
