### ISSUE TITLE
Cant get firmware to flash on device

### ISSUE THREAD

**Issue by jbishop129** [ludwig-v/wireless-carplay-dongle-reverse-engineering#78]
Hey guys, I was super excited to find this project! I have a new car with wired CarPlay, and wanted to move to wireless. I bought [one of these](https://amzn.to/3z7DXgq) "Carlinkit CPC200-U2W Plus". My car (2021 Acura RDX) recognizes it when plugging in, but the setup never completes successfully. One time I got it all working, but after restarting the car it never reconnects. Thought I'd just return it, as the seller really wasn't much help (send us logs, we'll look in to it. then nothing.)

Found this project, and thought there may be hope! but, I'm unable to get it to initiate the firmware flashing process. Here's what I've tried:

- Formatted a thumb drive FAT32
- Copied on to it both the `U2W_Update.img` and tried the `U2W_AUTOKIT_Update.img` file name as well
- Started up the Carlinkit device with external USB-C power (not connected to car or computer)
- Wait a few seconds for solid red light
- Insert USB thumb drive. Its' activity light flashes a couple times in the first 2 seconds of inserting it, then nothing.

I've let it sit up to 10 minutes, but no changes to the solid red light, no further USB thumb drive activity

I've tried a different thumb drive, tried formatting it both from a Win10 machine and from macOS machine. Tried different versions of the stock or modded firmware .img files from this repo, tried the different file naming conventions. I even ordered another Carlinkit device to see if the one I had was just faulty, it arrived with a slightly different firmware version, but has the exact same outcome in the above.

Wondering if I'm missing something obvious to you guys in either my setup or my attempt to USB flash new firmware?

**Comment by jbishop129** [comment]
... or, I can learn the difference between exFAT and FAT32. sigh. problem solved, operator error. 🤦

**Comment by qhuyduong** [comment]
@jbishop129
Hi I'm seeing the same issue. Do you mean using an exFAT USB work?

**Comment by jbishop129** [comment]
I was incorrectly formatting `exFAT`. The correct formatting is "MS DOS (FAT32)", otherwise it cannot read the filesystem.
