### ISSUE TITLE
Can upgrade/downgrade 'official' firmwares, but cant switch to Custom

### ISSUE THREAD

**Issue by jbishop129** [ludwig-v/wireless-carplay-dongle-reverse-engineering#79]
Hey all, I'm new to this so my apologies in advance for the basic problem: I have a Carlinkit CPC200-U2W Plus, and have figured out how to do the `U2W_Update.img` upgrades from thumb drive successfully. My unit shipped iwth 2020.12.25 firmware, I was able up to upgrade it to the latest stored here, 2021.04.26, and also able to do the 2020.11.10 rollback. What I cant seem to get working is the switch from 'stock' firmware over to custom. According to the README in 04.26 custom firmware, I need to roll back to 2020.11.10, which I was able to do. but from there, I cannot get it to accept the custom firmware file, which I download and rename to U2W_Update.img, dropped in my USB and plugged in, it just sits. But grabbing any of the official ones and dropping those in, the unit flashes green and starts the upgrade process.

What am I missing, in order to make the jump over to the custom firmwares? I have an actual functional problem, which I'll post as a separate issue. #80

**Comment by ludwig-v** [comment]
> My unit shipped iwth 2020.12.25 firmware

So it is a AUTOKIT version at first and rolling back to 2020.11.10 is changing you to AUTOKIT image so just rename your image "U2W_AUTOKIT_Update.img" (or just put both)

**Comment by jbishop129** [comment]
Thanks! Will try this out next week and reopen if further issues, otherwise assume your answer is the correct path.
