### ISSUE TITLE
No audio from music (Spotify), but can hear Siri talk

### ISSUE THREAD

**Issue by jbishop129** [ludwig-v/wireless-carplay-dongle-reverse-engineering#80]
HI all, I'm trying to make the switch over to the custom firmware, which maybe will solve my problem, and I have a question about that opened up too #79
I've tried on both 2020.11.10 and the latest official 2021.04.26: I can get my phone linked up, and it reconnects on startup, but it usually crashes the on-screen side after a few minutes, and in any case I never get any audio from my music playing. I tried Siri, and get her audio feedback, but Spotify, no sound. I've fiddled with the quality settings, normal vs compatible modes, CD / DVD, etc, to no avail. Anyone else ran in to this before?
Car is a 2021 Acura RDX

**Comment by ludwig-v** [comment]
It is linked to April update, downgrading to March or February version is fixing this black screen issue.

The purpose of this repo is not to fix manufacturer issues since only binaries are present inside firmwares, please use "Discussions" tab.

**Comment by jbishop129** [comment]
I can confirm downgrade to March firmware resolves the issue, thanks!
