### ISSUE TITLE
Problem doing the downgrade

### ISSUE THREAD

**Issue by freddygl** [ludwig-v/wireless-carplay-dongle-reverse-engineering#83]
Hi, i put the firmware in a usb formated in Fat32, afjet connect de carlinkit into power wall and waited for fixed red light. Them connect the usb in the dongle but nothing happens.

**Comment by freddygl** [comment]
Then when I reconnect the usb to the computer it tells me that there is a problem with the unit

**Comment by ludwig-v** [comment]
You have to use rollback images or downgrade script if CFW, the encryption method changed since March update. Also try with / without "_AUTOKIT"

**Comment by freddygl** [comment]
Hello, I have managed to install it, but now I have a new problem.

Everything works fine except music that doesn't play. Everything looks 
fine, but I can't change the volume on the iPhone and nothing sounds in 
the car.

I will install the original firm while I don't have a solution.

thx
