### ISSUE TITLE
Update not starting for some reason…

### ISSUE THREAD

**Issue by tonysprenk** [ludwig-v/wireless-carplay-dongle-reverse-engineering#90]
I have a carlinkit u2w plus running official firmware 03.06 and I’m trying to update with CFW but for some reason the update is not starting. I have copied the rollback image required for 03.06 to an external hard drive which is formatted in fat32. Is it because I’m using an external hard drive and not a usb flash drive?

**Comment by ludwig-v** [comment]
An external hard drive will probably have multiple partitions and / or drain too much power, use a USB Key instead

**Comment by tonysprenk** [comment]
I'm getting the same behaviour with a usb stick. What is the best way to format? at the moment I am using disk utility on a Mac...
