### ISSUE TITLE
Update not starting….

### ISSUE THREAD

**Issue by tonysprenk** [ludwig-v/wireless-carplay-dongle-reverse-engineering#91]
I opened an issue before but it was closed, sorry to repost. I am trying to update to latest CFW to my carlinkit CPC200-U2W Plus but the update process never starts, the red light stays on however long I wait. I’m using a 16gb usb stick formatted to FAT32 master boot record using disk utility on Mac. Any help would be greatly appreciated.

**Comment by ludwig-v** [comment]
It is a repo for reverse engineering and issues related to it, your issue is more a support request, please use Discussions tab instead.
