### ISSUE TITLE
Unable to upgrade to latest firmware

### ISSUE THREAD

**Issue by simps100** [ludwig-v/wireless-carplay-dongle-reverse-engineering#99]
Hi

I have a USB-C Carlinkit device - it is currently running a custom Firmware with the red UI version. A new firmware from July is available and would like to try it to see if it helps with issues.

OTA update was offered but didn’t work - I read may need to downgrade with script first, I tried that and when I go to 192.168.50.2 now it says I’m on Ver:2020.10.19.4242 and no OTA update is offered now.

Device still does not start update from usb with image called U2W_update.img - am I missing something after running the downgrade script?

EDIT: Just to add im not certain the downgrade happened correctly, it seemed too quick and the lights on dongle didnt flash - after i re-inserted USB into my pc i saw a text file saying version changed to 2020.10.19.4242 but from what i can see im still on the same firmware despite what it says?

thanks
Marc

**Comment by ludwig-v** [comment]
You didn't use the downgrade script but the one to write a custom firmware version.

To upgrade to >= 2021.03.06 from CFW, two solutions:
- Put **U2W_Update_2020.11.10.2138_ROLLBACK.img** on a USB Key and rename it to U2W_AUTOKIT_Update.img if Red UI or U2W_Update.img if Blue UI, then upgrade back to official 2021.03.06. Only then you can upgrade using **U2W_Update_2021.07.05.2308.img** renamed to U2W_Update.img
- Put this [script](https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/tree/master/Custom_Firmware/Scripts/RestoreNewEncryption_2021.03.06) (ARMimg_maker & U2W.sh) on a USB Key and **U2W_Update_2021.07.05.2308.img** and rename it to U2W_AUTOKIT_Update.img if Red UI or U2W_Update.img if Blue UI.
